name: KMS-Goettersystem
version: '${project.version}'
main: me.marc3308.kmsgoettersystem.goettersystem
api-version: '1.21'

permissions:
  gott:
    description: sprich als einer der götter
commands:
  gott:
    description: Sprich als ein gott
